<?php
$this->headTitle('Edit User');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Administration' => $this->url('admin'),
    'Users' => $this->url('admin.user.list'),
    'Edit' => $this->url('admin.user.edit'),
]);

/** @var \Laminas\Form\Form $form */
$form = $this->form->prepare();
$form->get('csrf')->setValue($this->token);
$form->get('submit')->setValue('Update');

/** @var \User\Entity\User $user */
$user = $this->user;

if ($user->isMfaEnabled() === false) {
    $form->get('mfa_enabled')->setAttribute('readonly', true);
}
?>
<div class="container">
    <h1>Edit User <?= $this->escapeHtml($user->getEmail()) ?></h1>
    <div class="row">
        <div class="col-md-6">
            <div class="widget">
                <?= $this->form()->openTag($form); ?>

                <div class="form-group">
                    <?= $this->formLabel($form->get('email')); ?>
                    <?= $this->formElement($form->get('email')); ?>
                    <?= $this->formElementErrors($form->get('email')); ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('full_name')); ?>
                    <?= $this->formElement($form->get('full_name')); ?>
                    <?= $this->formElementErrors($form->get('full_name')); ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('status')); ?>
                    <?= $this->formElement($form->get('status')); ?>
                    <?= $this->formElementErrors($form->get('status')); ?>
                </div>

                <div class="form-group">
                    <?php if($user->isMfaEnabled() === false): ?>
                        <p class="text-info">MFA cannot be enabled from here for another user.</p>
                    <?php else: ?>
                        <p class="text-danger">You may disable MFA for this user if required.</p>
                    <?php endif ?>
                    <?= $this->formLabel($form->get('mfa_enabled')); ?>
                    <?= $this->formElement($form->get('mfa_enabled')); ?>
                    <?= $this->formElementErrors($form->get('mfa_enabled')); ?>
                </div>


                <div class="form-group">
                    <?= $this->formLabel($form->get('roles')); ?>
                    <?= $this->formElement($form->get('roles')); ?>
                    <?= $this->formElementErrors($form->get('roles')); ?>
                </div>

                <?= $this->formElement($form->get('csrf')); ?>
                <?= $this->formElementErrors($form->get('csrf')); ?>
                <?= $this->formElement($form->get('submit')); ?>

                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>