<?php
    $contacts = $this->contacts;
    $organisation = $this->organisation;

    $this->headTitle('Contacts');

    $this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Organisations'  => $this->url('organisation.list'),
    $this->escapeHtml($organisation->getName())  => $this->url('organisation.view',['id' => $organisation->getUuid()]),
    'Contacts' => $this->url('contact.list', ['id' => $organisation->getUuid()]),
]);
?>
<h1>Contacts</h1>
<h2><?= $organisation->getName() ?></h2>
<a href="<?= $this->url('contact.create', ['id' => $organisation->getUuid()]) ?>"
    class="btn btn-primary btn-sm mb-2">New Contact</a>
<?php if (! empty($contacts)): ?>
<div class="list-group">
    <?php foreach ($contacts as $contact): ?>
        <div class="list-group-item">
            <?= $this->escapeHtml($contact->getFirstName()) ?>
            <?= $this->escapeHtml($contact->getLastName()) ?>
        </div>
    <?php endforeach ?>
</div>
<?php else: ?>
    <p class="text-info">
        No contacts are defined for <?= $this->escapeHtml($organisation->getName()) ?>
    </p>
<?php endif ?>