<?php
    /** @var \OrganisationContact\Entity\Contact[] $contacts */
    $contacts = $this->contacts;
    $organisation = $this->organisation;

    $this->headTitle('Contacts');

    $this->pageBreadcrumbs()->setItems([
        'Home' => $this->url('home'),
        'Organisations'  => $this->url('organisation.list'),
        $this->escapeHtml($organisation->getName())  => $this->url('organisation.view',['id' => $organisation->getUuid()]),
        'Contacts' => $this->url('contact.list', [
            'id' => $organisation->getUuid()
        ])
    ]);

    $contactCount = count($contacts);
?>
<div class="container-fluid">
    <h1>Contacts  <span class="badge badge-primary"><?= $contactCount ?></span></h1>
    <h2><?= $this->escapeHtml($organisation->getName()) ?></h2>

    <a href="<?= $this->url('contact.create', ['id' => $organisation->getUuid()]) ?>"
        class="btn btn-primary btn-sm mb-2">New Contact</a>

    <?php if (! empty($contacts)): ?>
        <table class="table table-dark striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Work</th>
                    <th scope="col">Mobile</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($contacts as $contact): ?>
                <tr>
                    <td>
                        <a href="<?= $this->url('contact.view', [
                            'id' => $organisation->getUuid(),
                            'contact_id' => $contact->getId()]) ?>">
                            <?= $this->escapeHtml($contact->getFirstName()) ?>
                            <?= $this->escapeHtml($contact->getLastName()) ?>
                        </a>
                    </td>
                    <td>
                        <?= $this->escapeHtml($contact->getWorkTelephone()) ?>
                    </td>
                    <td>
                        <?= $this->escapeHtml($contact->getMobileTelephone()) ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php else: ?>

            <p class="text-info">
                No contacts are defined for <?= $this->escapeHtml($organisation->getName()) ?>
            </p>

    <?php endif ?>
</div>
