<?php
    /** @var \Ticket\Entity\TicketResponse $response */
    $response = $this->response;

    $useSatisfaction = false;
?>
<p>
    Your case #<?= $response->getTicket()->getId() ?>
    (<?= $this->escapeHtml($response->getTicket()->getShortDescription()) ?>)
    has been updated.
</p>
<p>
    <strong>Comments:</strong>
</p>
<p>
    <?= $this->escapeHtml($response->getContact()->getFirstName()) ?>,
</p>
<p>
    Our team has indicated that your ticket has been <strong>resolved</strong>.
</p>
<p>
    There is no need to respond to this e-mail unless you believe the ticket has not been resolved. If there
    is no response from you, we will assume that the ticket has been resolved and the ticket will be
    automatically closed after 48 hours.
</p>
<p>
    Tracking ID: <?= $this->escapeHtml($response->getTicket()->getUuid()) ?>
</p>
<?php if ($useSatisfaction === true): ?>
    <table border="0" cellpadding="5" cellspacing="5" style="border-radius:5px;">
        <tr>
            <td align="center" valign="middle" style="background-color:#2c3d3a !important; border-color: #2c3d3a; color: #7db0ff; font-family:Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; letter-spacing:-.5px; line-height:150%; padding-top:15px; padding-right:30px; padding-bottom:15px; padding-left:30px; border-radius:5px;">
                <a href="#" target="_blank" style="color:#7db0ff; text-decoration:none;">Awesome</a>
            </td>
            <td align="center" valign="middle" style="background-color:#05352c !important; border-color: #05352c; color: #7db0ff; font-family:Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; letter-spacing:-.5px; line-height:150%; padding-top:15px; padding-right:30px; padding-bottom:15px; padding-left:30px; border-radius:5px;">
                <a href="#" target="_blank" style="color:#FFFFFF; text-decoration:none;">Just Okay</a>
            </td>
            <td align="center" valign="middle" style="background-color:#443639 !important; border-color: #443639; color: #7db0ff; font-family:Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; letter-spacing:-.5px; line-height:150%; padding-top:15px; padding-right:30px; padding-bottom:15px; padding-left:30px; border-radius:5px;">
                <a href="#" target="_blank" style="color:#FFFFFF; text-decoration:none;">Not Good</a>
            </td>
        </tr>
    </table>
<?php endif ?>