<?php


$action = $this->action ?? 'New';
$this->headTitle(sprintf('%s SLA', $action));

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Admin' => $this->url('admin'),
    'SLA' => $this->url('admin.sla_list'),
    $action => '',
]);

/** @var \Laminas\Form\FormInterface $form */
$form = $this->form->prepare();
?>
<h1>SLA Policies</h1>
<?= $this->form()->openTag($form) ?>
<div class="container-fluid">

    <div class="row">
        <div class="col">
            <div class="form-group">
                <?= $this->formLabel($form->get('name')) ?>
                <?= $this->formElement($form->get('name')) ?>
                <?= $this->formElementErrors($form->get('name')) ?>
            </div>
            <div class="form-group">
                <div class="form-group">
                    <?= $this->formLabel($form->get('business_hours')) ?>
                    <?= $this->formElement($form->get('business_hours')) ?>
                    <?= $this->formElementErrors($form->get('business_hours')) ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group row">
                <div class="col">
                    <?= $this->formLabel($form->get('p_critical_response_time')) ?>
                </div>
                <div class="col">
                    <?= $this->formElement($form->get('p_critical_response_time')) ?>
                    <?= $this->formElementErrors($form->get('p_critical_response_time')) ?>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group row">
                <div class="col">
                    <?= $this->formLabel($form->get('p_critical_resolve_time')) ?>
                </div>
                <div class="col">
                    <?= $this->formElement($form->get('p_critical_resolve_time')) ?>
                    <?= $this->formElementErrors($form->get('p_critical_resolve_time')) ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group row">
                <div class="col">
                    <?= $this->formLabel($form->get('p_urgent_response_time')) ?>
                </div>
                <div class="col">
                    <?= $this->formElement($form->get('p_urgent_response_time')) ?>
                    <?= $this->formElementErrors($form->get('p_urgent_response_time')) ?>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group row">
                <div class="col">
                    <?= $this->formLabel($form->get('p_urgent_resolve_time')) ?>
                </div>
                <div class="col">
                    <?= $this->formElement($form->get('p_urgent_resolve_time')) ?>
                    <?= $this->formElementErrors($form->get('p_urgent_resolve_time')) ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group row">
                <div class="col">
                    <?= $this->formLabel($form->get('p_high_response_time')) ?>
                </div>
                <div class="col">
                    <?= $this->formElement($form->get('p_high_response_time')) ?>
                    <?= $this->formElementErrors($form->get('p_high_response_time')) ?>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group row">
                <div class="col">
                    <?= $this->formLabel($form->get('p_high_resolve_time')) ?>
                </div>
                <div class="col">
                    <?= $this->formElement($form->get('p_high_resolve_time')) ?>
                    <?= $this->formElementErrors($form->get('p_high_resolve_time')) ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group row">
                <div class="col">
                    <?= $this->formLabel($form->get('p_medium_response_time')) ?>
                </div>
                <div class="col">
                    <?= $this->formElement($form->get('p_medium_response_time')) ?>
                    <?= $this->formElementErrors($form->get('p_medium_response_time')) ?>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group row">
                <div class="col">
                    <?= $this->formLabel($form->get('p_medium_resolve_time')) ?>
                </div>
                <div class="col">
                    <?= $this->formElement($form->get('p_medium_resolve_time')) ?>
                    <?= $this->formElementErrors($form->get('p_medium_resolve_time')) ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group row">
                <div class="col">
                    <?= $this->formLabel($form->get('p_low_response_time')) ?>
                </div>
                <div class="col">
                    <?= $this->formElement($form->get('p_low_response_time')) ?>
                    <?= $this->formElementErrors($form->get('p_low_response_time')) ?>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group row">
                <div class="col">
                    <?= $this->formLabel($form->get('p_low_resolve_time')) ?>
                </div>
                <div class="col">
                    <?= $this->formElement($form->get('p_low_resolve_time')) ?>
                    <?= $this->formElementErrors($form->get('p_low_resolve_time')) ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="form-group">
                <?= $this->formElement($form->get('submit')) ?>
                <?= $this->formElementErrors($form->get('submit')) ?>
                <?= $this->formHidden($form->get('id')) ?>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>
