<?php
$this->headTitle('SLA Business Hours');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Admin' => $this->url('admin'),
    'Business Hours' => $this->url('sla.list_business_hours'),
]);

/** @var \ServiceLevel\Entity\BusinessHours[] $businessHours */
$businessHours = $this->businessHours;
?>
<div class="container-fluid">
    <h1>Business Hours List</h1>
    <?php if (! empty($businessHours)): ?>
        <ul class="list-group">
        <?php foreach ($businessHours as $businessHour): ?>
            <li class="list-group-item">
                <a href="<?= $this->url('sla.edit_business_hours', ['id' => $businessHour->getId()]) ?>">
                    <?= $businessHour->getName() ?>
                </a>
            </li>
        <?php endforeach ?>
        </ul>
    <?php else: ?>
    <p class="text-info">No business hours have been defined.</p>
    <a href="<?= $this->url('sla.create_business_hours') ?>" class="btn btn-primary">Create New</a>
    <?php endif ?>
</div>
