<?php
    /** @var \ServiceLevel\Entity\BusinessHours[] $businessHours */
    $businessHours = $this->businessHours;
?>
<div class="container-fluid">
    <h1>Business Hours List</h1>
    <?php if (! empty($businessHours)): ?>
        <ul class="list-group">
        <?php foreach ($businessHours as $businessHour): ?>
            <li class="list-group-item">
                <a href="<?= $this->url('admin.sla_edit_business_hours', ['id' => $businessHour->getId()]) ?>">
                    <?= $businessHour->getName() ?>
                </a>
            </li>
        <?php endforeach ?>
        </ul>
    <?php else: ?>
    <p class="text-info">No business hours have been defined.</p>
    <?php endif ?>
</div>
