<?php
    $form = $this->form->prepare();
?>
<div class="container">
    <h1>Change Password</h1>
    <?= $this->form()->openTag($form) ?>
    <div class="form-group">
        <?= $this->formLabel($form->get('current_password')) ?>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-lock fa-fw"></i></span>
            </div>
            <?= $this->formElement($form->get('current_password')) ?>
        </div>
        <?= $this->formElementErrors($form->get('current_password')) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('new_password')) ?>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-lock fa-fw"></i></span>
            </div>
            <?= $this->formElement($form->get('new_password')) ?>
        </div>
        <?= $this->formElementErrors($form->get('new_password')) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('confirm_new_password')) ?>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-lock fa-fw"></i></span>
            </div>
            <?= $this->formElement($form->get('confirm_new_password')) ?>
        </div>
        <?= $this->formElementErrors($form->get('confirm_new_password')) ?>
    </div>

    <div class="form-group">
        <?= $this->formElement($form->get('submit')) ?>
        <?= $this->formElementErrors($form->get('submit')) ?>
    </div>
    <?= $this->form()->closeTag() ?>
</div>

