<?php
$this->headTitle('Add Permission');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Administration' => $this->url('admin'),
    'Permissions' => $this->url('admin.permission.list'),
]);

/** @var \Laminas\Form\Form $form */
$form = $this->form->prepare();

$form->get('csrf')->setValue($this->token);
?>
<div class="container">
    <h1>Add Permission</h1>
    <p>
        Please fill out the following form and click the <i>Create</i> button.
    </p>
    <div class="row">
        <div class="col-md-6">
            <?= $this->form()->openTag($form); ?>

            <div class="form-group">
                <?= $this->formLabel($form->get('name')); ?>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('description')); ?>
                <?= $this->formElement($form->get('description')); ?>
                <?= $this->formElementErrors($form->get('description')); ?>
            </div>

            <?= $this->formElement($form->get('csrf')); ?>
            <?= $this->formElementErrors($form->get('csrf')); ?>
            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
