<?php
$this->headTitle('View Permission');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Administration' => $this->url('admin'),
    'Permissions' => $this->url('admin.permission.list'),
    $this->escapeHtml($permission->getName()) => '',
]);

/** @var \User\Entity\Permission $permission */
$permission = $this->permission;
?>
<div class="container">
    <h1>View Permission "<?= $this->escapeHtml($permission->getName()); ?>"</h1>
    <div class="row">
        <div class="col-md-6">
            <table class="table table-striped table-bordered">
                <tr>
                    <th>ID:</th>
                    <td><?= $this->escapeHtml($permission->getId()) ?></td>
                </tr>
                <tr>
                    <th>Name:</th>
                    <td><?= $this->escapeHtml($permission->getName()) ?></td>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
                </tr>
                <tr>
                    <th>Date Created:</th>
                    <td><?= $this->escapeHtml($permission->getDateCreated()) ?></td>
                </tr>
            </table>
        </div>
    </div>
    <a href="<?= $this->url('admin.permission.list'); ?>" class="btn btn-primary">
        <i class="fas fa-list"></i> Permissions
    </a>
</div>