<?php
$this->headTitle('Create Organisation');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Organisation' => $this->url('organisation.list'),
    'Create Organisation' => $this->url('organisation.create'),
]);

$form = $this->form->prepare();
/** @var \Laminas\Form\Fieldset $domainFieldset */

;

?>
<div class="container">
    <h1>Create Organisation</h1>
    <?= $this->form()->openTag($form) ?>
    <div class="form-group">
        <?= $this->formLabel($form->get('name')) ?>
        <?= $this->formElement($form->get('name')) ?>
        <?= $this->formElementErrors($form->get('name', ['class' => 'help-block'])) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($form->get('domain')) ?>
        <?= $this->formElement($form->get('domain')) ?>
        <?= $this->formElementErrors($form->get('domain')) ?>
    </div>
    <div class="form-group">
        <?= $this->formElement($form->get('submit')) ?>
        <a href="<?= $this->url('organisation.list') ?>" class="btn btn-secondary">Cancel</a>
    </div>
    <?= $this->form()->closeTag() ?>
</div>