<?php
$this->inlineScript()->appendFile('/js/bootstrap-autocomplete.min.js');
$this->headTitle('Organisations');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Organisation' => $this->url('organisation.list'),
    'List' => $this->url('organisation.list'),
]);

/** @var \Laminas\Form\FormInterface $form */
$form = $this->form->prepare();
?>
<div class="container-fluid h-100">
    <div class="row">
        <div class="col">
            <?= $this->form()->openTag($form) ?>
            <h1>Select Organisation</h1>
            <div class="form-group">
                <?= $this->formLabel($form->get('organisation')) ?>
                <?= $this->formElement($form->get('organisation')) ?>
                <?= $this->formElementErrors($form->get('organisation')) ?>
            </div>
            <div class="form-group">
                <?= $this->formElement($form->get('submit')) ?>
                <?= $this->formElementErrors($form->get('submit')) ?>
            </div>
            <?= $this->form()->closeTag() ?>
        </div>
    </div>
</div>
<?= $this->inlineScript()->captureStart() ?>
$(function() {
    $('.basicAutoSelect').attr('placeholder','type to search...').autoComplete();
});
<?= $this->inlineScript()->captureEnd() ?>
