<?php
$this->headTitle('Edit Role');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Administration' => $this->url('admin'),
    'Edit Role' => $this->url('admin.role.list'),
    $this->escapeHtml($this->role->getName()) => $this->url('admin.role.list'),
]);

$form = $this->form->prepare();
$form->get('submit')->setValue('Update');
$form->get('csrf')->setValue($this->token);
?>
<div class="container">
    <h1>Edit Role "<?= $this->escapeHtml($this->role->getName()); ?>"</h1>
    <div class="row">
        <div class="col-md-6">
            <?= $this->form()->openTag($form); ?>

            <div class="form-group">
                <?= $this->formLabel($form->get('name')); ?>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('description')); ?>
                <?= $this->formElement($form->get('description')); ?>
                <?= $this->formElementErrors($form->get('description')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('inherit_roles')); ?>
                <?= $this->formElement($form->get('inherit_roles')); ?>
                <?= $this->formElementErrors($form->get('inherit_roles')); ?>
            </div>

            <?= $this->formElement($form->get('csrf')); ?>
            <?= $this->formElementErrors($form->get('csrf')); ?>

            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>