<?php
$this->headTitle('Edit Role Permissions');


$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Administration' => $this->url('admin'),
    'Roles' => $this->url('admin.role.list'),
    $this->escapeHtml($this->role->getName()) => $this->url('admin.role-view', ['id' => $role->getId()]),
    'Permissions' => ''

]);


/** @var \Laminas\Form\Form $form */
$form = $this->form->prepare();
$form->get('csrf')->setValue($this->token);
?>
<div class="container">
    <h1>Edit Permissions of <?= $this->escapeHtml($role->getName()); ?></h1>
    <div class="row">
        <div class="col-md-8">
            <?= $this->form()->openTag($form); ?>
            <table class="table table-striped table-bordered">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                </tr>
                <?php foreach ($this->allPermissions as $permission):
                    $element = $form->get('permissions')->get($permission->getName());
                    ?>
                    <tr>
                        <td>
                            <div class="checkbox">
                                <label><input type="checkbox" name="<?= $this->escapeHtmlAttr($element->getName()) ?>"
                                              value="<?= $this->escapeHtmlAttr($element->getCheckedValue()) ?>"
                                        <?php if ($element->isChecked()) echo 'checked'?>
                                        <?php if ($element->getAttribute('disabled')) echo 'disabled'?>>
                                    <?= $this->escapeHtml($element->getLabel()) ?>
                                </label>
                                <?= $this->formElementErrors($element); ?>
                            </div>
                        </td>
                        <td>
                            <?= $this->escapeHtml($permission->getDescription()) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
            <?= $this->formElement($form->get('csrf')); ?>
            <?= $this->formElementErrors($form->get('csrf')); ?>
            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>