<?php
    /** @var \Laminas\Form\FormInterface $form */
    $form = $this->form->prepare();

    /** @var \Ticket\Entity\Queue $queue */
    $queue = $this->queue;
?>
<div class="container-fluid">
    <?= $this->form()->openTag($form) ?>
    <div class="row">
        <div class="col">
            <h1>Assign Queue Members</h1>
            <h2><?= $this->escapeHtml($queue->getName()) ?> Queue</h2>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <?= $this->formLabel($form->get('members')) ?>
        </div>
        <div class="col-sm-10">
            <?= $this->formElement($form->get('members')) ?>
            <?= $this->formElementErrors($form->get('members')) ?>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">&nbsp;</div>
        <div class="col-sm-10">
            <?= $this->formElement($form->get('submit')) ?>
            <?= $this->formElementErrors($form->get('submit')) ?>
        </div>
    </div>
    <?= $this->form()->closeTag() ?>
</div>
