<?php
    /** @var \Ticket\Entity\Queue[] $queues
     */
    $queues = $this->queues;
?>
<h1>Ticket Queues</h1>
<div class="container-fluid">
    <div class="list-group">
        <?php foreach ($queues as $queue): ?>
        <div class="list-group-item">
            <a href="<?= $this->url('admin.queue_edit', ['id' => $queue->getId()]) ?>">
                <?= $this->escapeHtml($queue->getName()) ?>
            </a>
        </div>
        <?php endforeach; ?>
    </div>
</div>
