<?php
    /** @var \Ticket\Entity\Queue[] $queues
     */
    $queues = $this->queues;

$this->headTitle('Queues');
$this->pageBreadcrumbs()->setItems([
    'Home'           => $this->url('home'),
    'Administration' => $this->url('admin'),
    'Queues'         => $this->url('admin.queue_list'),
]);
?>
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h1>Ticket Queues</h1>
        </div>
    </div>
    <?php foreach ($queues as $queue): ?>
    <div class="row bg-secondary mb-4 p-3 rounded">
            <div class="col-md-8 align-middle">
                <a href="<?= $this->url('admin.queue_edit', ['id' => $queue->getId()]) ?>">
                    <?= $this->escapeHtml($queue->getName()) ?>
                </a>
            </div>
            <div class="col-md-4">
                <a href="<?= $this->url('admin.queue_assign', ['id' => $queue->getId()]) ?>"
                   class="btn btn-primary btn-sm">
                    Assign Members
                </a>
            </div>
        </div>
    <?php endforeach; ?>
</div>
