<?php
    $this->inlineScript()->appendFile('/js/timeago.js');
?>
<div class="container-fluid">
    <?php if (count($this->tickets) === 0): ?>
    <div class="row">
        <div class="col">
            <p class="text-info">No tickets have been created.</p>
        </div>
    </div>
    <?php endif ?>
    <?php
    /** @var \Ticket\Entity\Ticket $ticket */
    foreach ($this->tickets as $ticket): ?>
        <div class="row ticket-list-item bg-dark">
            <div class="col-sm-6 ">
                <a href="<?= $this->url('ticket.view', ['ticket_id' => $ticket->getUuid()]) ?>">
                    <?= $this->escapeHtml($ticket->getShortDescription()) ?>
                </a>
                <span class="text-muted">#<?= $this->escapehtml($ticket->getId()) ?><br></span>
                <span class="text-muted">Raised by</span>
                    <?= $this->escapeHtml($ticket->getContact()->getFirstName()) ?>
                    <?= $this->escapeHtml($ticket->getContact()->getLastName()) ?> /
                    <a href="<?= $this->url('ticket.list',
                        [ 'org_id' => $ticket->getOrganisation()->getUuid() ],
                        [],
                        null,
                        [ 'reuse_result_params' => false] ) ?>">
                    <?= $this->escapeHtml($ticket->getOrganisation()->getName()) ?>
                        <?php if ($ticket->hasSla()): ?>
                        <small><span class="badge badge-info">SLA</span></small>
                        <?php endif ?>
                    </a>
                <br>
                <span class="text-muted">
                    <small>
                    Due
                    <time class="timeago" datetime="<?= $ticket->getDueDate() ?>">
                    <?= $ticket->getDueDate() ?>
                    </time>,
                    created
                    <time class="timeago" datetime="<?= $ticket->getCreatedAt() ?>">
                        <?= $ticket->getCreatedAt() ?>
                    </time>
                        by
                        <?php
                            if (! empty($ticket->getAgent())) {
                                echo $this->escapeHtml($ticket->getAgent()->getFullName());
                            } elseif (empty($ticket->getAgent()) && !empty($ticket->getContact())) {
                                echo sprintf('%s %s',
                                $this->escapeHtml($ticket->getContact()->getFirstName()),
                                $this->escapeHtml($ticket->getContact()->getLastName())
                                );
                            }
                        ?>
                    </small>
                </span>
            </div>
            <div class="col-sm-2">
                <span class="text-muted">Last Response</span><br/>
                <?php if (null !== $ticket->getLastResponseDate()): ?>
                <small>
                    <time class="timeago text-muted"
                          datetime="<?= $this->localDate($ticket->getLastResponseDate(), 'Y-m-d H:i:s') ?>">
                      <?= $this->localDate($ticket->getLastResponseDate()) ?>
                    </time>
                </small>
                <?php else: ?>
                    <?php if ($ticket->hasSla()): ?>
                    <small class="text-warning">
                        Response due <time class="timeago" datetime="<?= $ticket->getResponseDueDate() ?>">
                            <?= $ticket->getResponseDueDate() ?>
                        </time>
                    </small>
                    <?php else: ?>
                        <small class="text-muted">No response</small><br>
                    <?php endif ?>
                <?php endif ?>
                <br>
                <?php
                    $dt = new \DateTime('now');
                    $dtDue = new \DateTime($ticket->getDueDate());

                    if ($dt->getTimestamp() >  $dtDue->getTimestamp()
                        && $ticket->getStatus()->getId() <= $ticket::STATUS_ON_HOLD) : ?>
                        <span class="badge badge-danger">Overdue</span>
                    <?php endif
                ?>

            </div>
            <div class="col-sm-1">
                &nbsp;
            </div>
            <div class="col-sm-3">
                <div class="row">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-4">
                            <small>
                                <span class="text-muted">Assigned</span>
                            </small>
                        </div>
                        <div class="col text-center">
                            <small>
                                <?= $ticket->getQueue()->getName() ?>
                            </small>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    <div class="row status text-center">
                        <div class="col-4 text-muted text-left">
                            <small>Status</small>
                        </div>
                        <div class="col">
                            <small>
                            <span class="<?= strtolower($this->escapeHtml($ticket->getStatus()->getDescription())) ?>">
                                <?= $this->escapeHtml($ticket->getStatus()->getDescription()) ?>
                            </span>
                            </small>
                        </div>
                    </div>
                </div>
                <?php if ($ticket->hasSla() ) : ?>
                <div class="col-sm-12">
                    <div class="row priority text-center">
                        <div class="col-4 text-muted text-left"><small>Priority</small></div>
                        <div class="col <?= $this->escapeHtml(strtolower($ticket->getPriority()->getName())) ?>">
                            <?= $this->escapeHtml($ticket->getPriority()->getName()) ?>
                        </div>
                    </div>
                </div>
                <?php endif ?>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
    <div class="row">
        <div class="col mt-4">
            <?php
                if ($this->pageCount > 1) {
                    echo $this->paginationControl($this->tickets,'Sliding','app::partial/paginator');
                }
            ?>
        </div>
    </div>
</div>
<?php
$this->inlineScript()->captureStart();
echo <<<JS
// <script>
    $(document).ready(function() {
        $(function() {
            jQuery.timeago.settings.allowFuture = true;
            $('.timeago').timeago();
        });
    });
// </script>
JS;
$this->inlineScript()->captureEnd();
?>
