<?php

    $this->inlineScript()->appendFile('/js/timeago.js');


/** @var \Ticket\Entity\Ticket $ticket */
    $ticket = $this->ticket;

    /** @var \Ticket\Entity\TicketResponse[] $responses */
    $responses = $this->responses;

    $responseForm = $this->responseForm->prepare();
    $recentTickets = $this->recentTickets;
?>
    <div class="row">
        <div class="col-md-8">
            <div class="card bg-dark mb-2">
                <div class="card-header">
                    <h1>Ticket #<?= $ticket->getId() ?></h1>
                </div>
                <div class="card-body">
                    <p>
                        <?= $this->escapeHtml($ticket->getShortDescription()) ?>
                    </p>
                    <hr class="bg-light">
                    <p>
                        <strong>
                            <?= $this->escapeHtml($ticket->getContact()->getFirstName()) ?>
                            <?= $this->escapeHtml($ticket->getContact()->getLastName()) ?>
                        </strong>
                        Reported via <?= $ticket::getSourceTextFromCode($ticket->getSource()) ?>
                        <span class="text-muted"> (<?= $ticket->getQueue()->getName() ?> Queue)</span>
                    </p>
                </div>
            </div>

            <div class="row mb-2 mt-2">
                <div class="col">
                    <span class="text-muted">Status:</span>
                    <?= $ticket->getStatus()->getDescription() ?>
                </div>
                <div class="col">
                    <span class="text-muted">Impact:</span>
                    <?= $ticket::getImpactUrgencyText($ticket->getImpact()) ?>
                </div>
                <div class="col">
                    <span class="text-muted">Urgency:</span>
                    <?= $ticket::getImpactUrgencyText($ticket->getUrgency()) ?>
                </div>
            </div>

            <div class="card mb-2">
                <div class="card-header">
                    <strong>Issue</strong>
                </div>
                <div class="card-body">
                    <?= nl2br($this->escapeHtml($ticket->getLongDescription())) ?>
                    <hr class="bg-light">
                </div>
            </div>

            <div class="card mb-2">
                <div class="card-header">
                    Last Responses
                </div>
                <div class="card-body">
                    <small>
                    <?php foreach ($responses as $response): ?>
                        <span class="text-muted">
                            <time class="timeago " datetime="<?= $this->escapeHtml($response->getResponseDate()) ?>">
                                <?= $this->escapeHtml($response->getResponseDate()) ?>
                            </time>
                            by
                            <?php if (null !== $response->getAgent()) {
                                echo $this->escapeHtml($response->getAgent()->getFullName());
                            } elseif ((null === $response->getAgent()) && ($response->getContact() !== null)) {
                                echo sprintf('%s %s', $this->escapeHtml($response->getContact()->getFirstName()),
                                $this->escapeHtml($response->getContact()->getLastName()));
                            }
                            ?>
                        </span>
                        <br>
                        <?= nl2br($this->escapeHtml($response->getResponse())) ?>
                    <hr>
                    <?php endforeach; ?>
                    </small>
                </div>
            </div>

                <div class="card mb-2">
                <div class="card-header">
                    Add Response
                </div>
                <div class="card-body">

                    <?= $this->form()->openTag($responseForm) ?>

                    <div class="form-group">
                        <?= $this->formLabel($responseForm->get('response')); ?>
                        <?= $this->formElement($responseForm->get('response')); ?>
                        <?= $this->formElementErrors()->render($responseForm->get('response'), [
                                'class' => 'help-block' ]); ?>
                    </div>
                    <div class="custom-control custom-checkbox text-right">
                        <?= $this->formCheckbox($responseForm->get('is_public')); ?>
                        <?= $this->formLabel($responseForm->get('is_public')); ?>
                        <?= $this->formElementErrors()->render($responseForm->get('is_public'), ['class' => 'help-block']); ?>
                    </div>

                    <button type="submit" class="btn btn-primary" name="submit" value="save">
                        <i class="fas fa-save fa-fw"></i> Save
                    </button>

                    <?php if ($ticket->getStatus()->getId() !== $ticket::STATUS_ON_HOLD): ?>
                    <button type="submit" class="btn btn-warning" name="submit" value="save_hold">
                        <i class="fas fa-hand-paper fa-fw"></i> Save + Hold
                    </button>
                    <?php elseif ($ticket->getStatus()->getId() === $ticket::STATUS_ON_HOLD): ?>
                        <button type="submit" class="btn btn-warning" name="submit" value="save_hold">
                            <i class="fas fa-hand-paper fa-fw"></i> Save (remove hold)
                        </button>
                    <?php endif ?>

                    <button id="submit" type="submit" class="btn btn-success" name="submit" value="save_resolve">
                        <i class="fas fa-check fa-fw"></i> Save + Resolve
                    </button>

                    <?= $this->formElementErrors($responseForm->get('submit')) ?>
                    <?= $this->form()->closeTag() ?>

                </div>
            </div>

        </div> <!-- // col -->

        <div class="col-md-4">
            <div class="card mb-2">
                <div class="card-header">Contact Info</div>
                <div class="card-body">
                    <p>
                        <small class="text-light">Name:</small><br/>
                        <?= $this->escapeHtml($ticket->getContact()->getFirstName()) ?>
                        <?= $this->escapeHtml($ticket->getContact()->getLastName()) ?>
                    </p>

                    <?php if (!empty($ticket->getContact()->getWorkTelephone())): ?>
                        <p>
                            <small class="text-light">Work Tel:</small><br/>
                            <a href="tel:<?= $this->escapeHtml($ticket->getContact()->getWorkTelephone()) ?>">
                                <?= $this->escapeHtml($ticket->getContact()->getWorkTelephone()) ?>
                            </a>
                        </p>
                    <?php endif ?>

                    <?php if (!empty($ticket->getContact()->getMobileTelephone())): ?>
                        <p>
                            <small class="text-light">Mobile:</small><br/>
                            <a href="tel:<?= $this->escapeHtml($ticket->getContact()->getMobileTelephone()) ?>">
                                <?= $this->escapeHtml($ticket->getContact()->getMobileTelephone()) ?>
                            </a>
                        </p>
                    <?php endif ?>

                    <p>
                        <small class="text-light">E-mail Address:</small><br/>
                        <a href="mailto:<?= $this->escapeHtml($ticket->getContact()->getWorkEmail()) ?>">
                            <?= $this->escapeHtml($ticket->getContact()->getWorkEmail()) ?>
                        </a>
                    </p>
                </div>
            </div>

            <div class="card mb-2">
                <div class="card-header">
                    <?= $this->escapeHtml($ticket->getContact()->getFirstName()) ?>'s recent tickets
                </div>
                <div class="card-body">
                    <?php
                    /** @var \Ticket\Entity\Ticket $recentTicket */
                    foreach ($recentTickets as $recentTicket) {

                            if ($recentTicket->getId() === $ticket->getId()) {
                                continue;
                            }
                    ?>
                        <p>
                            <small class="text-muted">
                                <time class="timeago" datetime="<?= $recentTicket->getCreatedAt() ?>">
                                    <?= $recentTicket->getCreatedAt() ?>
                                </time>
                            </small><br/>
                            <a href="<?= $this->url('ticket.view', ['ticket_id' => $recentTicket->getUuid()]) ?>">
                                <?= $this->escapeHtml($recentTicket->getShortDescription()) ?>
                            </a>
                        </p>
                    <?php } ?>
                </div>
            </div>

        </div> <!-- // col -->

    </div>

<?php
$this->inlineScript()->captureStart();
echo <<<JS
// <script>
    $(document).ready(function() {
        $(function() {
             jQuery.timeago.settings.allowFuture = true;
            $('.timeago').timeago();
        });
    });
// </script>
JS;
$this->inlineScript()->captureEnd();
?>
