<?php
    $this->inlineScript()->appendFile('/js/timeago.js');

    /** @var \Ticket\Entity\Ticket $ticket */
    $ticket = $this->ticket;

    /** @var \Ticket\Entity\TicketResponse[] $responses */
    $responses = $this->responses;

    $recentTickets = $this->recentTickets;
    $responseForm = $this->responseForm->prepare();

    // prepare address
    $siteAddress = array_filter([
            'name'              => $this->escapeHtml($ticket->getSite()->getName()) ?: null,
            'street_address'    => $this->escapeHtml($ticket->getSite()->getStreetAddress()) ?: null,
            'street_address2'   => $this->escapeHtml($ticket->getSite()->getStreetAddress2()) ?: null,
            'town'              => $this->escapeHtml($ticket->getSite()->getTown()) ?: null,
            'city'              => $this->escapeHtml($ticket->getSite()->getCity()) ?: null,
            'county'            => $this->escapeHtml($ticket->getSite()->getCounty()) ?: null,
            'postcode'          => $this->escapeHtml($ticket->getSite()->getPostalCode()) ?: null,
            'country'           => $this->escapehtml($ticket->getSite()->getCountry()->getName()),
    ]);
?>
    <div class="row">
        <div class="col-md-8">
            <div class="card bg-dark mb-2">
                <div class="card-header">
                    <h1>Ticket #<?= $ticket->getId() ?></h1>
                </div>
                <div class="card-body">
                    <p>
                        <?= $this->escapeHtml($ticket->getShortDescription()) ?>
                    </p>
                    <hr class="bg-light">
                    <p>
                        <strong>
                            <?= $this->escapeHtml($ticket->getContact()->getFirstName()) ?>
                            <?= $this->escapeHtml($ticket->getContact()->getLastName()) ?>
                        </strong>
                        Reported via <?= $ticket::getSourceTextFromCode($ticket->getSource()) ?>
                        <span class="text-muted">
                            (<?= $this->escapeHtml($ticket->getQueue()->getName()) ?> Queue)
                        </span>
                    </p>
                </div>
            </div>

            <div class="row mb-2 mt-2">
                <div class="col">
                    <span class="text-muted">Status:</span>
                    <?= $this->escapeHtml($ticket->getStatus()->getDescription()) ?>
                </div>
                <div class="col">
                    <span class="text-muted">Impact:</span>
                    <?= $ticket::getImpactUrgencyText($ticket->getImpact()) ?>
                </div>
                <div class="col">
                    <span class="text-muted">Urgency:</span>
                    <?= $ticket::getImpactUrgencyText($ticket->getUrgency()) ?>
                </div>
            </div>

            <div class="card mb-2">
                <div class="card-header">
                    <strong>Issue</strong>
                </div>
                <div class="card-body">
                    <?= nl2br($this->escapeHtml($ticket->getLongDescription())) ?>
                    <hr class="bg-light">
                </div>
            </div>

            <div class="card mb-2">
                <div class="card-header">
                    Last Responses
                </div>
                <div class="card-body">
                    <?php foreach ($responses as $response): ?>
                    <p class="text-muted">
                        <small>
                            <time class="timeago " datetime="<?= $this->escapeHtml($response->getResponseDate()) ?>">
                                <?= $this->escapeHtml($response->getResponseDate()) ?>
                            </time>
                            by
                            <?php if (null !== $response->getAgent()) {
                                echo $this->escapeHtml($response->getAgent()->getFullName());
                            } elseif ((null === $response->getAgent()) && ($response->getContact() !== null)) {
                                echo sprintf('%s %s', $this->escapeHtml($response->getContact()->getFirstName()),
                                $this->escapeHtml($response->getContact()->getLastName()));
                            }
                            ?>
                        </small>
                    </p>
                    <p>
                        <?= nl2br($this->escapeHtml($response->getResponse())) ?>
                    </p>
                    <hr>
                    <?php endforeach; ?>
                </div>
            </div>

            <div class="card mb-2">
                <div class="card-header">
                    Add Response
                </div>
                <div class="card-body">
                    <?= $this->form()->openTag($responseForm) ?>
                    <div class="form-group">
                        <?= $this->formLabel($responseForm->get('response')); ?>
                        <div class="custom-control custom-checkbox text-left">
                            <?= $this->formCheckbox($responseForm->get('is_public')); ?>
                            <?= $this->formLabel($responseForm->get('is_public')); ?>
                            <?= $this->formElementErrors()->render($responseForm->get('is_public'), ['class' => 'help-block']); ?>
                        </div>
                        <?= $this->formElement($responseForm->get('response')); ?>
                        <?= $this->formElementErrors()->render($responseForm->get('response'), [
                                'class' => 'help-block' ]); ?>
                    </div>

                    <button type="submit" class="btn btn-primary" name="submit" value="save">
                        <i class="fas fa-save fa-fw"></i> Save
                    </button>

                    <?php if ($ticket->getStatus()->getId() !== $ticket::STATUS_ON_HOLD): ?>
                    <button type="submit" class="btn btn-warning" name="submit" value="save_hold">
                        <i class="fas fa-hand-paper fa-fw"></i> Save + Hold
                    </button>
                    <?php elseif ($ticket->getStatus()->getId() === $ticket::STATUS_ON_HOLD): ?>
                        <button type="submit" class="btn btn-warning" name="submit" value="save_hold">
                            <i class="fas fa-hand-paper fa-fw"></i> Save (remove hold)
                        </button>
                    <?php endif ?>

                    <button id="submit" type="submit" class="btn btn-success" name="submit" value="save_resolve">
                        <i class="fas fa-check fa-fw"></i> Save + Resolve
                    </button>

                    <?= $this->formElementErrors($responseForm->get('submit')) ?>

                    <a class="btn btn-danger float-right" href="<?= $this->url('ticket.edit',
                        ['ticket_id' => $ticket->getUuid()]) ?>">
                        <i class="fas fa-clone fa-fw"></i> Edit Ticket
                    </a>

                    <a class="btn btn-secondary float-right" href="<?= $this->url('ticket.clone',
                        ['ticket_id' => $ticket->getUuid()]) ?>">
                        <i class="fas fa-hand-paper fa-fw"></i> Clone Ticket
                    </a>


                    <?= $this->form()->closeTag() ?>

                </div>
            </div>
        </div> <!-- // col -->

        <div class="col-md-4">
            <div class="card mb-2">
                <div class="card-header">
                    Ticket Info
                </div>
                <div class="card-body">
                    <p>
                        <small class="text-light">Ticket Status</small><br/>
                        <?= $ticket->getStatus()::getStatusTextFromId($ticket->getStatus()->getId()) ?>
                    </p>
                    <p class="<?= $ticket->hasSla() ? 'priority' : null?>">
                        <small class="text-light">Ticket Type</small><br/>
                        <?php if ($ticket->hasSla()): ?>
                        <span class="<?= strtolower($ticket->getPriority()->getName()) ?>">
                            <?= $ticket->getType()::getStatusTextFromId($ticket->getType()->getId()); ?> /
                            <?= $ticket->getPriority()->getName() ?> Priority
                        </span>
                        <?php else: ?>
                        <span class="text-muted bg-secondary pl-2 pr-2">
                           <?= $ticket->getType()::getStatusTextFromId($ticket->getType()->getId()); ?>
                        </span>
                        <?php endif ?>
                    </p>

                    <?php if ($ticket->hasSla()): ?>
                    <p>
                        <small class="text-light">Response Due</small><br>
                        <time class="timeago"
                              datetime="<?= $this->localDate($ticket->getResponseDueDate(), 'Y-m-d H:i:s') ?>">
                            <?= $this->localDate($ticket->getResponseDueDate()) ?>
                        </time>
                    </p>
                    <?php endif ?>
                    <p>
                        <small class="text-light">Due Date</small><br>
                        <?php if ($ticket->getDueDate() !== null): ?>
                        <time class="timeago" datetime="<?= $this->localDate($ticket->getDueDate(), 'Y-m-d H:i:s') ?>">
                            <?= $this->localDate($ticket->getDueDate()) ?>
                        <?php else: ?>
                            ???
                        <?php endif ?>
                    </p>
                </div>
            </div>

            <div class="card mb-2">
                <div class="card-header">Contact Info</div>
                <div class="card-body">
                    <p>
                        <small class="text-light">Name:</small><br/>
                        <?= $this->escapeHtml($ticket->getContact()->getFirstName()) ?>
                        <?= $this->escapeHtml($ticket->getContact()->getLastName()) ?>
                    </p>

                    <?php if (!empty($ticket->getContact()->getWorkTelephone())): ?>
                        <p>
                            <small class="text-light">Work Tel:</small><br/>
                            <a href="tel:<?= $this->escapeHtml($ticket->getContact()->getWorkTelephone()) ?>">
                                <?= $this->escapeHtml($ticket->getContact()->getWorkTelephone()) ?>
                            </a>
                        </p>
                    <?php endif ?>

                    <?php if (!empty($ticket->getContact()->getMobileTelephone())): ?>
                        <p>
                            <small class="text-light">Mobile:</small><br/>
                            <a href="tel:<?= $this->escapeHtml($ticket->getContact()->getMobileTelephone()) ?>">
                                <?= $this->escapeHtml($ticket->getContact()->getMobileTelephone()) ?>
                            </a>
                        </p>
                    <?php endif ?>

                    <p>
                        <small class="text-light">E-mail Address:</small><br/>
                        <a href="mailto:<?= $this->escapeHtml($ticket->getContact()->getWorkEmail()) ?>">
                            <?= $this->escapeHtml($ticket->getContact()->getWorkEmail()) ?>
                        </a>
                    </p>

                    <p>
                        <small class="text-light">Site Address:</small><br/>
                        <?= implode('<br>', $siteAddress); ?>
                    </p>

                    <?php if (null !== $ticket->getSite()->getTelephone()): ?>
                    <p>
                        <small class="text-light">Site Telephone:</small><br/>
                        <a href="tel:<?= $this->escapeHtml($ticket->getSite()->getTelephone()) ?>">
                            <?= $this->escapeHtml($ticket->getSite()->getTelephone()) ?>
                        </a>
                    </p>
                    <?php endif ?>
                </div>
            </div>

            <div class="card mb-2">
                <div class="card-header">
                    <?= $this->escapeHtml($ticket->getContact()->getFirstName()) ?>'s recent tickets
                </div>
                <div class="card-body">
                    <?php
                    /** @var \Ticket\Entity\Ticket $recentTicket */
                    foreach ($recentTickets as $recentTicket) {

                            if ($recentTicket->getId() === $ticket->getId()) {
                                continue;
                            }
                    ?>
                        <p>
                            <small class="text-muted">
                                <time class="timeago" datetime="<?= $recentTicket->getCreatedAt() ?>">
                                    <?= $recentTicket->getCreatedAt() ?>
                                </time>
                            </small><br/>
                            <a href="<?= $this->url('ticket.view', ['ticket_id' => $recentTicket->getUuid()]) ?>">
                                <?= $this->escapeHtml($recentTicket->getShortDescription()) ?>
                            </a>
                        </p>
                    <?php } ?>
                </div>
            </div>
        </div> <!-- // col -->

    </div>

        <?php
$this->inlineScript()->captureStart();
echo <<<JS
// <script>
    $(document).ready(function() {
        $(function() {
             jQuery.timeago.settings.allowFuture = true;
            $('.timeago').timeago();
        });
    });
// </script>
JS;
$this->inlineScript()->captureEnd();
?>
