<?php require 'header.phtml'; ?>
    <header class="app-header">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Brand -->
                    <a class="navbar-brand" href="<?=$this->url('home')?>">
                        <img src="/img/casilium-white.svg" alt="Casilium Service Management" height="24" />
                    </a>
                </div>
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="<?= $this->url('organisation.list') ?>" class="nav-link">
                                <i class="fa fa-book"></i> Organisations
                            </a>
                        </li>
                    </ul>

                    <?php if ($this->identity() != null): ?>


                        <ul class="nav navbar ml-auto">
                            <li class="nav-item dropdown d-md-down-none"></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                    <span style="color: #ffffff"><i class="fas fa-user"></i> <?= $this->escapeHtml($this->identity()->getName()); ?></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="<?= $this->url('account'); ?>"><i class="fas fa-user-cog fa-fw"></i> Account Settings</a>
                                    <a class="dropdown-item" href="<?= $this->url('logout'); ?>"><i class="fas fa-sign-out-alt fa-fw"></i> Logout</a>
                                    <?php if ($this->identity()->hasRole('administrator')): ?>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="<?= $this->url('admin'); ?>"><i class="fas fa-cogs fa-fw"></i> Admin</a>
                                    <?php endif; ?>
                                </div>
                            </li>
                        </ul>
                    <?php endif; ?>


                </div>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <!-- Breadcrumbs -->
            <div class="mt-2 mb-2">
                <?= $this->pageBreadcrumbs()->render(); ?>
            </div>
            <?=$this->content?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
            <hr />
            <p>
                &copy; <?=date('Y')?> <a href="https://sheridan.co.uk/">Sheridan Computers Limited</a>.
            </p>
        </div>
    </footer>

<?php require 'footer.phtml'; ?>