<?php require_once 'header.phtml' ?>

<div class="d-flex" id="wrapper">
    <!-- Sidebar -->
    <div class="bg-dark" id="sidebar-wrapper">
        <div class="sidebar-heading mb-4">
            <a href="<?= $this->url('home') ?>">
                <img src="/img/casilium-white.svg" alt="Casilium Service Management" class="img-fluid" />
            </a>
        </div>
        <div class="list-group list-group-flush">
            <a href="#" class="list-group-item list-group-item-action bg-dark">
                <i class="fas fa-tachometer-alt fa-fw mr-2"></i> Dashboard
            </a>
            <a href="<?= $this->url('organisation.list') ?>"
               class="list-group-item list-group-item-action bg-dark">
                <i class="fas fa-users fa-fw mr-2"></i> Organisations
            </a>
            <a href="<?= $this->url('ticket.list', [], [], null, ['reuse_result_params' => false]) ?>"
               class="list-group-item list-group-item-action bg-dark">
                <i class="fas fa-ticket-alt fa-fw mr-2"></i> Tickets
            </a>
        </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="<?= $this->url('home') ?>">Home</a>
                    </li>
                    <?php if ($this->identity() != null): ?>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user fa-fw"></i> <?= $this->escapeHtml($this->identity()->getName()); ?>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="<?= $this->url('account') ?>"><i class="fas fa-user-cog fa-fw"></i> Account Settings</a>
                            <?php if ($this->identity()->hasRole('administrator')): ?>
                                <a class="dropdown-item" href="<?= $this->url('admin') ?>"><i class="fas fa-cogs fa-fw"></i> Admin</a>
                            <?php endif; ?>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="<?= $this->url('logout') ?>"#>
                                <i class="fas fa-sign-out-alt fa-fw"></i> Logout
                            </a>
                        </div>
                    </li>
                    <?php endif ?>
                </ul>
            </div>
        </nav>

        <div class="container-fluid">
            <!-- Breadcrumbs -->
            <div class="mt-2 mb-2">
                <?= $this->pageBreadcrumbs()->render() ?>
            </div>
            <?= $this->content ?>
        </div>
    </div>
    <!-- /#page-content-wrapper -->
</div>
<?php
$this->inlineScript()->captureStart();
echo <<<JS
$("#menu-toggle").click(function(e) {
    e.preventDefault();
    $('#wrapper').toggleClass("toggled");
});
JS;
$this->inlineScript()->captureEnd();
?>

<?php require_once 'footer.phtml' ?>
