<?php
$this->headLink()
    ->prependStylesheet('/css/style.css')
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.13.0/css/all.css')
    //->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css');
    ->prependStylesheet('/css/bootstrap.min-dark.css');
$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.5.1.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <?=$this->headTitle('Casilium')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <style>
        .casilium-blue, h2 a, h2 a:hover { color: #447799; }
        .navbar-brand { padding: 0; }
        .navbar-brand img { margin: -.5rem 0; filter: brightness(0) invert(1); }
    </style>
    <?= $this->headStyle() ?>
</head>
<body>
<?php if ($flashes = $this->flash()) :?>
    <div class="alert alert-info alert-dismissible fade show">
        <ul class="list-unstyled">
            <?php foreach($flashes as $type => $message) : ?>
                <li><?php echo $message; ?></li>
            <?php endforeach; ?>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endif; ?>