<?php $this->headTitle('Home'); ?>
<div class="jumbotron mt-3">
    <h1>Welcome to <span class="casilium-blue">Casilium</span></h1>
    <h2>Open Source Enterprise Level Help Desk Software</h2>
    <p>
        Built on Mezzio by the <a href="https://getlaminas.org/">Laminas Project</a>,
        an open-source continuation of Zend Framework.
    </p>
    <hr>
    <p>
        Our goal is to help businesses and organisations become effective at supporting their users, customers,
        and partners. We do it by developing surprisingly simple, user-friendly and
        <span style="color: #009900">FREE</span> help desk software.
    </p>
</div>